version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: "master"
    reviewers:
      - "RuiMoreira1"
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: "master"
    reviewers:
      - "RuiMoreira1"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: "master"
    reviewers:
      - "RuiMoreira1"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    target-branch: "master"
    reviewers:
      - "RuiMoreira1"
  
     
