version: "3.9"

services:
    postgres:
        container_name: postgres
        image: postgres:14.5-alpine3.16
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.14
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@ds.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - 4321:80
        depends_on:
            - postgres

    django:
        container_name: django
        build:
            context: ./backend
        command: sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py loaddata populate.json &&
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/app/backend
        ports:
            - 8000:8000
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        depends_on:
            - postgres

    react:
        container_name: react
        build:
            context: ./frontend
        depends_on:
            - django
        volumes:
            - ./frontend/src:/app/frontend/src
        environment:
            - REACT_APP_BACKEND_HOST=127.0.0.1
            - REACT_APP_BACKEND_PORT=8000
