"""Module generated by django to create the shiftplanner app"""
from django.apps import AppConfig


class ShiftplannerConfig(AppConfig):
    """
    Configuration for the shiftplanner app
    """

    default_auto_field = "django.db.models.BigAutoField"
    name = "src.shiftplanner"
